# Generated by Django 5.2.4 on 2025-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
